FROM golang:1.22.1-bullseye AS builder
ENV CGO_ENABLED=1
WORKDIR /
COPY ./sample/echo-pb sample/echo-pb
COPY ./sample/echo-plain sample/echo-plain
WORKDIR /sample/echo-plain
RUN go build -trimpath -ldflags="-s -w" -o frontend frontend.go
FROM alpine:latest
RUN apk add gcompat
# Copy the built binary from the builder stage
COPY --from=builder /sample/echo-plain/frontend /frontend
# Set the entrypoint command to run the binary
CMD ["/frontend"]
