apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  clusterIP: 10.96.88.88
  ports:
  - name: frontend
    port: 80
    targetPort: 8080
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - image: appnetorg/echo-plain-frontend
        name: frontend-grpc
  selector:
    matchLabels:
      app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  clusterIP: 10.96.77.76
  ports:
  - name: server
    port: 9000
    targetPort: 9000
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  template:
    metadata:
      name: server
      labels:
        app: server
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: appnetorg/echo-plain-server
        name: server-grpc
        volumeMounts:
        - name: server-storage
          mountPath: "/data"
      volumes:
      - name: server-storage
        persistentVolumeClaim:
          claimName: echo-pvc
  selector:
    matchLabels:
      app: server
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: echo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /tmp/appnet
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: echo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
---